#!/usr/bin/env python3

from argparse import ArgumentParser
import logging
import flickr

parser = ArgumentParser()
parser.add_argument('-v', '--verbosity', action='count', default=0,
                    help='increase output verbosity (-vv for debug)')
args = parser.parse_args()

logging_levels = [logging.WARNING, logging.INFO, logging.DEBUG]
logging.basicConfig(level=logging_levels[args.verbosity])

print('Flickr Addicts pool size:', flickr.group.get_pool_size('76535076@N00'))
